"""Inintiol

Revision ID: 592b08c4a5d2
Revises: ed0eb45eeaa5
Create Date: 2024-08-14 17:15:51.969295

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '592b08c4a5d2'
down_revision: Union[str, None] = 'ed0eb45eeaa5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email', sa.String(), nullable=False))
    op.drop_column('user', 'gmail')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('gmail', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('user', 'email')
    # ### end Alembic commands ###
